base16-sublime-theme: 
    extension: .sublime-theme
    output:

base16-color-scheme: 
    extension: .sublime-color-scheme
    output: color-schemes

base16-widget:
    extension: .stTheme
    output: widgets

base24-sublime-theme: 
    extension: .sublime-theme
    output:
    supported-systems: [base24]

base24-color-scheme: 
    extension: .sublime-color-scheme
    output: color-schemes
    supported-systems: [base24]

base24-widget:
    extension: .stTheme
    output: widgets
    supported-systems: [base24]

widget-settings:
    extension: .sublime-theme
    output: widgets
    supported-systems: [base16, base24]
